refactor(env): simplify ternary statement for dsync feature flag
boxyhq/saas-starter-kit pull request #1183
Opened 2024-03-27 17:10 UTC by Musyonchez

This PR addresses a code style issues in the `env.ts` configuration file. Previously, you were using an unneeded ternary statement to set the flag. However, this can be simplified to a single logical NOT operation.

To improve readability, we've updated the code to avoid the unneeded ternary statement.

Changes include:
- Updating the feature flag in `env.ts` to use a logical NOT operation instead of a ternary statement.

This change should make the code in `env.ts` easier to read and maintain.

2024-03-28 09:11 UTC, ukrocks007 requested changes

2024-03-28 09:11 UTC, ukrocks007 commented on lib/env.ts
> +    !!(process.env.DISABLE_NON_BUSINESS_EMAIL_SIGNUP === 'true'),
```suggestion
    process.env.DISABLE_NON_BUSINESS_EMAIL_SIGNUP === 'true',
```

2024-03-28 09:11 UTC, ukrocks007 commented on lib/env.ts
> +  hideLandingPage: !!(process.env.HIDE_LANDING_PAGE === 'true'),
```suggestion
  hideLandingPage: process.env.HIDE_LANDING_PAGE === 'true',
```

2024-03-28 09:11 UTC, ukrocks007 commented on lib/env.ts
> +    sso: !(process.env.FEATURE_TEAM_SSO === 'false'),
```suggestion
    sso: process.env.FEATURE_TEAM_SSO !== 'false',
```

2024-03-28 09:11 UTC, ukrocks007 commented on lib/env.ts
> +        : !!(process.env.STRIPE_SECRET_KEY && process.env.STRIPE_WEBHOOK_SECRET),
```suggestion
        : Boolean(process.env.STRIPE_SECRET_KEY && process.env.STRIPE_WEBHOOK_SECRET),
```

2024-03-31 08:33 UTC, Musyonchez commented
I am in a place with slow internet i will fix the errors tomorrow.

2024-04-01 16:46 UTC, Musyonchez commented
I have made the changes as suggested by @ukrocks007. Please check.

2024-04-01 17:35 UTC, ukrocks007 approved these changes

2024-04-01 17:50 UTC, deepakprabhakara approved these changes

2024-04-01 20:43 UTC, merged