Config docker to run local more easy
boxyhq/saas-starter-kit pull request #42
Opened 2022-10-14 12:42 UTC by Cristuker

I add a docker compose file to the project and update the readme to make more easy for the beginners run the database. With this PR they only need to install docker compose and run `docker-compose up -d` no need to install db or search for how to do this.

PS: i leave a example how to build a url for postgres

2022-10-14 22:32 UTC, Cristuker commented
This feature is ready for review

2022-10-15 03:09 UTC, devkiran requested changes

2022-10-15 03:09 UTC, devkiran commented on README.md
>  #### 5. Set up database schema
Can you change the heading, now both step 5 and 6 has same heading. I would like to mark the `docker-compose` step as optional if the developers want to spin on a database using Docker or they can use any database they want.

2022-10-15 03:09 UTC, devkiran commented on docker-compose.yml
> +      POSTGRES_DB: starter-kit
Rename the database name to `saas-starter-kit`

2022-10-15 14:17 UTC, devkiran approved these changes

2022-10-15 14:20 UTC, merged

2022-10-15 14:20 UTC, devkiran commented
Thank you for your time and this contribution.