feat: update password reset email template
boxyhq/saas-starter-kit pull request #448
Opened 2023-08-31 20:20 UTC by Young-Einstein10

# What's in this PR?

This PR contains a rebuild of the password reset html template using [React.email](https://react.email/). Solves [Issue 418](https://github.com/boxyhq/saas-starter-kit/issues/418)

# Screenshots

![Screenshot 2023-08-31 at 20 08 42](https://github.com/boxyhq/saas-starter-kit/assets/45533201/8bd3c683-5d4b-4f0d-85cf-787c35807e5b)

2023-09-01 04:49 UTC, devkiran commented
@Young-Einstein10 Great work! First email template looks good. You can work on the remaining templates if you wish.

A couple of requests:
- Can we make the header and footer into a separate React component? That way we can reuse it across all the email templates.
- Don't hard code the value `BoxyHQ`, it should read from app settings `@/lib/app`. You can add the additional settings in the `@/lib/app` file if you need.
- Please pin the dependencies in `package.json` to a specific version.
- Can you try making the logo dimension to 50 x 50?

2023-09-01 08:26 UTC, Young-Einstein10 commented
Thanks for the feedback. 
Sure, I'd keep these in mind while working on the rest.

2023-09-04 05:09 UTC, devkiran requested changes

2023-09-04 12:08 UTC, devkiran approved these changes

2023-09-04 12:08 UTC, merged