Add a "show password" icon to the Login and Signup pages #558"show password" icon to the Login and Signup pages
boxyhq/saas-starter-kit pull request #568
Opened 2023-10-04 18:55 UTC by vivekBoii

![Screenshot from 2023-10-05 00-24-52](https://github.com/boxyhq/saas-starter-kit/assets/115945472/36366e8e-1427-49de-9462-faa85e444321)

2023-10-06 15:42 UTC, devkiran requested changes

2023-10-06 15:42 UTC, devkiran commented on components/auth/Join.tsx
> +  const[isactive,wasactive]=useState(true);
```suggestion
  const [showPassword, setShowPassword] = useState(false);
```

2023-10-06 15:43 UTC, vivekBoii commented on components/auth/JoinWithInvitation.tsx
> +      <div className='flex'>
yes sir it will try to follow your one from next time

2023-10-07 06:21 UTC, devkiran commented on components/auth/JoinWithInvitation.tsx
> +      <div className='flex'>
Thanks. Please review all the suggestions.

2023-10-07 06:28 UTC, closed without merging