Implement Minimum Password Length Check on Update Password Page #590
boxyhq/saas-starter-kit pull request #599
Opened 2023-10-09 12:50 UTC by ShubhamSingh-S34

min current password required to send PUT request to '/api/password' is now changed to 7 which is the minimun length of password required while signing up. client side validation is done . Tell if server side validation is required.

password length 6. Button is disabled
![Screenshot (52)](https://github.com/boxyhq/saas-starter-kit/assets/100158059/185fe243-59d3-455a-940d-d42b936a39cc)

password length 7 . Button is enabeled
![Screenshot (53)](https://github.com/boxyhq/saas-starter-kit/assets/100158059/6b326347-41d4-48df-8914-783cafeea234)

2023-10-09 13:44 UTC, NathanTarbert commented
Hi @ShubhamSingh-S34, would you mind modifying your submission?  [NIST](https://pages.nist.gov/800-63-3/sp800-63-3.html) recommends a minimum password length of 8. 
I am adding this to #590.

2023-10-09 17:59 UTC, ShubhamSingh-S34 commented
Done

2023-10-10 03:46 UTC, devkiran requested changes

2023-10-10 03:46 UTC, devkiran commented on components/account/UpdatePassword.tsx
> +  currentPassword: Yup.string().required().min(8),
```suggestion
  currentPassword: Yup.string().required(),
```
Remove the length check on the `currentPassword`.

2023-10-10 05:57 UTC, closed without merging

2023-10-10 05:57 UTC, devkiran commented
Already covered in another PR.