email fix - members
boxyhq/saas-starter-kit pull request #601
Opened 2023-10-09 17:08 UTC by Kiran-Alex

Now When the user is adding members it gives a response if the email format is invalid

2023-10-11 03:47 UTC, devkiran requested changes

2023-10-11 03:47 UTC, devkiran commented on components/invitation/InviteMember.tsx
> +      email: Yup.string().email().required('Email is required'), // Added error message
```suggestion
      email: Yup.string().email().required('Email is required'),
```

2023-10-11 03:47 UTC, devkiran commented on components/invitation/InviteMember.tsx
>        role: availableRoles[0].id,
We have added prettier format to standardise formatting across the source files. Please merge main and then run `npm run format`.

2023-10-11 03:47 UTC, devkiran commented on components/invitation/InviteMember.tsx
> +            )}
Can you please align the error message properly on the UI?

2023-10-11 05:49 UTC, Kiran-Alex commented
The Error Is Now Shown as This, Please Review This and I'm actively looking for the feedback
![image](https://github.com/boxyhq/saas-starter-kit/assets/98690069/12024942-30b4-4aa5-a14b-a1840b5037ee)

2023-10-11 06:30 UTC, devkiran commented
@Kiran-Alex Can you please check the error state on other input? Here is how error state looks on login page.

![Login-BoxyHQ](https://github.com/boxyhq/saas-starter-kit/assets/4593041/776f8ac7-9e4b-4af4-9ebe-431d7e23b79c)

2023-10-12 05:01 UTC, Kiran-Alex commented
The UI and error State is Updated, Similar to the Signup

![image](https://github.com/boxyhq/saas-starter-kit/assets/98690069/e1ce727f-95eb-40c1-864e-480f58ea569f)

2023-10-12 06:09 UTC, devkiran requested changes
- Can you run `npm run format` to format the code?
- Let's remove the `onBlur` property and handle the validation after the form submission.

Other than that, it looks good to me. We'll merge it once you make the changes.

2023-10-12 06:28 UTC, Kiran-Alex commented
email fix #3 - Now the error validation is done when the user clicks on the button instead of any place on the modal.

2023-10-12 06:37 UTC, devkiran approved these changes

2023-10-12 06:37 UTC, merged