e2e login test
boxyhq/saas-starter-kit pull request #609
Opened 2023-10-10 11:42 UTC by emmacode

e2e login test

2023-10-10 12:40 UTC, emmacode commented
@devkiran 
Please I need your review and below is what I'm trying to do

1. In docker-compose.yml I created a test database to use for the tests
2. In logn.spec.ts when the Sign in button is clicked. It is not redirecting to the dashboard. When the button is clicked the loading is still true therefore not navigating to the dashboard. This error as well [Failed to load resource: the server responded with a status of 401 (Unauthorized)]

Screenshot of screen
[Screenshot](https://drive.google.com/drive/folders/1aCQzrELG8_eGUmFtvQGSAPeFanCt0YHi?usp=sharing)

2023-10-11 17:56 UTC, devkiran commented
Thanks @emmacode for the PR. Let's review this and get back to you soon.

2023-10-25 16:52 UTC, niwsa commented on yarn.lock
Could you remove this lock file? We only maintain a single package-lock.json file.

2023-10-26 04:05 UTC, niwsa requested changes
@emmacode Left a few comments. Let me know in case you have any queries.

2023-10-26 05:54 UTC, emmacode commented on yarn.lock
yes thanks

2023-11-16 08:17 UTC, devkiran commented
@emmacode Can you run and check if you have the same issue now? I have made some changes.

2024-01-10 10:57 UTC, niwsa approved these changes

2024-01-11 11:53 UTC, merged