feat:added toogle password function
boxyhq/saas-starter-kit pull request #611
Opened 2023-10-11 08:22 UTC by jatingodnani

#558 @deepakprabhakara @devkiran check my pr.added toogle password

2023-10-11 14:37 UTC, deepakprabhakara commented
@jatingodnani Can you please format the files, `npm run format`

2023-10-11 14:47 UTC, jatingodnani commented
done @devkiran

2023-10-11 17:50 UTC, devkiran requested changes

2023-10-11 17:50 UTC, devkiran commented on components/auth/Join.tsx
> +import { MdVisibility, MdVisibilityOff } from 'react-icons/md';
Can we use `heroicons` instead? We'll remove the react-icons from the project.

2023-10-11 17:50 UTC, devkiran commented on components/auth/Join.tsx
> +  const handlepasswordvisibility = () => {
```suggestion
  const hadlePasswordVisibility = () => {
```

2023-10-11 17:50 UTC, devkiran commented on components/auth/Join.tsx
> +            onClick={handlepasswordvisibility}
```suggestion
            onClick={hadlePasswordVisibility}
```

2023-10-11 17:50 UTC, devkiran commented on components/auth/Join.tsx
> +            onClick={handlepasswordvisibility}
Add property `type='button'` to the button, otherwise it will submit the form when click the icon.

2023-10-11 17:59 UTC, jatingodnani commented on components/auth/Join.tsx
> +  const handlepasswordvisibility = () => {
what is the problem in this

2023-10-11 18:02 UTC, devkiran commented on components/auth/Join.tsx
> +  const handlepasswordvisibility = () => {
Please use camelCase for method name.

2023-10-11 18:03 UTC, jatingodnani commented on components/auth/Join.tsx
> +  const handlepasswordvisibility = () => {
Ok

2023-10-11 18:38 UTC, jatingodnani commented
@devkiran  done

2023-10-12 04:36 UTC, devkiran requested changes
Can you please look at the following issues?

- Eye icon is not visible in the light mode
- Can we reduce the size of the icon? Maybe from 6 to 5. Looks a bit large at the moment.
- Can we add the similar feature to JoinWithInvitation as well?
- Maybe you can move this to a separate component and use it login/join pages? (Eg: TogglePasswordVisibility.tsx)

2023-10-12 04:36 UTC, devkiran commented on package.json
>      "@hookform/resolvers": "3.3.1",
Heroicon is already installed in the project, can you revert the changes to package.json/package-lock.json?

2023-10-12 05:35 UTC, jatingodnani commented
@devkiran check

2023-10-12 05:56 UTC, jatingodnani commented
@devkiran is their any problem in my code

2023-10-12 05:57 UTC, devkiran approved these changes

2023-10-12 05:59 UTC, merged

2023-10-12 06:00 UTC, devkiran commented
@jatingodnani Thanks for the PR.

2023-10-12 06:00 UTC, devkiran commented
@jatingodnani Thanks for the PR.