Install Sentry
boxyhq/saas-starter-kit pull request #695
Opened 2023-10-26 07:04 UTC by devkiran

2023-11-12 02:17 UTC, deepakprabhakara approved these changes

2023-11-12 02:18 UTC, deepakprabhakara commented
If NEXT_PUBLIC_SENTRY_DSN is not defined then what is the behaviour?

2023-11-12 02:18 UTC, deepakprabhakara requested changes
If NEXT_PUBLIC_SENTRY_DSN is not defined then what is the behaviour?

2023-11-13 05:03 UTC, devkiran commented
From the doc 

> If that variable also does not exist, the SDK will just not send any events.

https://docs.sentry.io/platforms/javascript/guides/nextjs/configuration/options/#dsn

2023-11-13 23:18 UTC, deepakprabhakara approved these changes

2023-11-13 23:35 UTC, merged